### ISSUE TITLE
Login and register forms should only be displayed on demand

### ISSUE THREAD

**Issue by jaceklaskowski** [jaceklaskowski/librarian-clojure#25]
The login and register forms should only be visible when a user wants to log in or register. They're a sort of a clutter right now when the only reason I visited a page is to know the books and their reviews.

I think there should be a menu with buttons for the forms which would be displayed centered after a corresponding button is clicked. Just an idea. I like how it's organized in GitHub where the logout, account settings and the other buttons are grouped together on the top right-hand side. We need to follow the pattern.

**Comment by konrad-garus** [comment]
I agree with moving "logout" to the top menu, but right now there's so little content for non-users that the login form does not seem to add too much clutter. 

It depends what else we add in there, and how much we want to encourage social interactions. I mean, Facebook and Twitter do welcome you with a big login screen.

**Comment by jaceklaskowski** [comment]
I've just come across http://www.goodreads.com/ and guess I'd love having the forms like it does or something similar (wish we had a contact with a web designer).

**Comment by zoldar** [comment]
After a short code archeology session, I was still unable to point to a single commit, so I'm just closing it.
