### ISSUE TITLE
Use set-connection! in librarian-clojure.db

### ISSUE THREAD

**Issue by zoldar** [jaceklaskowski/librarian-clojure#33]
I thought that the code there could be made a bit less cluttered using congomongo's global connection handling (using set-connection! etc.). Every database related operation starts with assertion assuring that connection exists, so all those (when _database-connection_ ..) checks would be rather redundant (it should blow up as soon as possible anyway). Are there any particular obejctions to such way of handling db connectivity?

**Comment by jaceklaskowski** [comment]
If it doesn't break the code, and is the right way to handle db connections, I'm fine with the proposal. Show the code and it's gonna be easier to decide.

**Comment by zoldar** [comment]
I've sent a pull request with proposed changes. Externally, behavior remains unchanged.
