### ISSUE TITLE
Exclude database/heroku credentials from dvcs tracking

### ISSUE THREAD

**Issue by zoldar** [jaceklaskowski/librarian-clojure#35]
Wouldn't it set a better example if actual credentials were put outside git's control?

Here's one way in which it could be accomplished:

http://squirrel.pl/blog/2012/10/01/configuration-files-in-clojure/

Edit: Come to think of it, there would have to be some additional hook adding proper configuration on deployment to Heroku.

**Comment by jaceklaskowski** [comment]
Bingo! I've been thinking about replacing the credentials for the past couple of hours once I committed the latest changes. I'm working on it. I think it requires some Heroku voodoo.

**Comment by zoldar** [comment]
Looks like the general way to do this is using env variables:

https://devcenter.heroku.com/articles/multiple-environments

EDIT: This one is more to the point: https://devcenter.heroku.com/articles/mongohq

**Comment by jaceklaskowski** [comment]
Fixed in e9036ae.
